// Code generated by protoc-gen-go.
// source: protos/golang.yacloud.eu/apis/urlmapper/urlmapper.proto
// DO NOT EDIT!

/*
Package urlmapper is a generated protocol buffer package.

It is generated from these files:
	protos/golang.yacloud.eu/apis/urlmapper/urlmapper.proto

It has these top-level messages:
	JsonMapping
	GetJsonMappingRequest
	JsonMappingResponse
	JsonMappingResponseList
	DomainList
	ServiceID
	AnyHostMapping
	AnyMappingRequest
	AnyMappingResponse
*/
package urlmapper

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "golang.conradwood.net/apis/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JsonMapping struct {
	ID        uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Domain    string `protobuf:"bytes,2,opt,name=Domain" json:"Domain,omitempty"`
	Path      string `protobuf:"bytes,3,opt,name=Path" json:"Path,omitempty"`
	ServiceID string `protobuf:"bytes,4,opt,name=ServiceID" json:"ServiceID,omitempty"`
	GroupID   string `protobuf:"bytes,5,opt,name=GroupID" json:"GroupID,omitempty"`
}

func (m *JsonMapping) Reset()                    { *m = JsonMapping{} }
func (m *JsonMapping) String() string            { return proto.CompactTextString(m) }
func (*JsonMapping) ProtoMessage()               {}
func (*JsonMapping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *JsonMapping) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *JsonMapping) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *JsonMapping) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *JsonMapping) GetServiceID() string {
	if m != nil {
		return m.ServiceID
	}
	return ""
}

func (m *JsonMapping) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

type GetJsonMappingRequest struct {
	Domain string `protobuf:"bytes,1,opt,name=Domain" json:"Domain,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=Path" json:"Path,omitempty"`
}

func (m *GetJsonMappingRequest) Reset()                    { *m = GetJsonMappingRequest{} }
func (m *GetJsonMappingRequest) String() string            { return proto.CompactTextString(m) }
func (*GetJsonMappingRequest) ProtoMessage()               {}
func (*GetJsonMappingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetJsonMappingRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *GetJsonMappingRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type JsonMappingResponse struct {
	Mapping     *JsonMapping `protobuf:"bytes,1,opt,name=Mapping" json:"Mapping,omitempty"`
	GRPCService string       `protobuf:"bytes,2,opt,name=GRPCService" json:"GRPCService,omitempty"`
}

func (m *JsonMappingResponse) Reset()                    { *m = JsonMappingResponse{} }
func (m *JsonMappingResponse) String() string            { return proto.CompactTextString(m) }
func (*JsonMappingResponse) ProtoMessage()               {}
func (*JsonMappingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *JsonMappingResponse) GetMapping() *JsonMapping {
	if m != nil {
		return m.Mapping
	}
	return nil
}

func (m *JsonMappingResponse) GetGRPCService() string {
	if m != nil {
		return m.GRPCService
	}
	return ""
}

type JsonMappingResponseList struct {
	Responses []*JsonMappingResponse `protobuf:"bytes,1,rep,name=Responses" json:"Responses,omitempty"`
}

func (m *JsonMappingResponseList) Reset()                    { *m = JsonMappingResponseList{} }
func (m *JsonMappingResponseList) String() string            { return proto.CompactTextString(m) }
func (*JsonMappingResponseList) ProtoMessage()               {}
func (*JsonMappingResponseList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *JsonMappingResponseList) GetResponses() []*JsonMappingResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type DomainList struct {
	Domains []string `protobuf:"bytes,1,rep,name=Domains" json:"Domains,omitempty"`
}

func (m *DomainList) Reset()                    { *m = DomainList{} }
func (m *DomainList) String() string            { return proto.CompactTextString(m) }
func (*DomainList) ProtoMessage()               {}
func (*DomainList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DomainList) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

type ServiceID struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *ServiceID) Reset()                    { *m = ServiceID{} }
func (m *ServiceID) String() string            { return proto.CompactTextString(m) }
func (*ServiceID) ProtoMessage()               {}
func (*ServiceID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServiceID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// via _api this can get mapped in
type AnyHostMapping struct {
	ID        uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Path      string `protobuf:"bytes,2,opt,name=Path" json:"Path,omitempty"`
	ServiceID string `protobuf:"bytes,3,opt,name=ServiceID" json:"ServiceID,omitempty"`
}

func (m *AnyHostMapping) Reset()                    { *m = AnyHostMapping{} }
func (m *AnyHostMapping) String() string            { return proto.CompactTextString(m) }
func (*AnyHostMapping) ProtoMessage()               {}
func (*AnyHostMapping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AnyHostMapping) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AnyHostMapping) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *AnyHostMapping) GetServiceID() string {
	if m != nil {
		return m.ServiceID
	}
	return ""
}

type AnyMappingRequest struct {
	Path        string `protobuf:"bytes,1,opt,name=Path" json:"Path,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=ServiceName" json:"ServiceName,omitempty"`
}

func (m *AnyMappingRequest) Reset()                    { *m = AnyMappingRequest{} }
func (m *AnyMappingRequest) String() string            { return proto.CompactTextString(m) }
func (*AnyMappingRequest) ProtoMessage()               {}
func (*AnyMappingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AnyMappingRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *AnyMappingRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type AnyMappingResponse struct {
	Path string `protobuf:"bytes,1,opt,name=Path" json:"Path,omitempty"`
}

func (m *AnyMappingResponse) Reset()                    { *m = AnyMappingResponse{} }
func (m *AnyMappingResponse) String() string            { return proto.CompactTextString(m) }
func (*AnyMappingResponse) ProtoMessage()               {}
func (*AnyMappingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AnyMappingResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*JsonMapping)(nil), "urlmapper.JsonMapping")
	proto.RegisterType((*GetJsonMappingRequest)(nil), "urlmapper.GetJsonMappingRequest")
	proto.RegisterType((*JsonMappingResponse)(nil), "urlmapper.JsonMappingResponse")
	proto.RegisterType((*JsonMappingResponseList)(nil), "urlmapper.JsonMappingResponseList")
	proto.RegisterType((*DomainList)(nil), "urlmapper.DomainList")
	proto.RegisterType((*ServiceID)(nil), "urlmapper.ServiceID")
	proto.RegisterType((*AnyHostMapping)(nil), "urlmapper.AnyHostMapping")
	proto.RegisterType((*AnyMappingRequest)(nil), "urlmapper.AnyMappingRequest")
	proto.RegisterType((*AnyMappingResponse)(nil), "urlmapper.AnyMappingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for URLMapper service

type URLMapperClient interface {
	// get json mapping for URL and user
	GetJsonMappingWithUser(ctx context.Context, in *GetJsonMappingRequest, opts ...grpc.CallOption) (*JsonMappingResponse, error)
	// get json mapping for URL
	GetJsonMapping(ctx context.Context, in *GetJsonMappingRequest, opts ...grpc.CallOption) (*JsonMappingResponse, error)
	// get all json mappings
	GetJsonMappings(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*JsonMappingResponseList, error)
	// add a json mapping
	AddJsonMapping(ctx context.Context, in *JsonMapping, opts ...grpc.CallOption) (*common.Void, error)
	// get all domains "mapped" to jsonmultiplexer
	GetJsonDomains(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*DomainList, error)
	// get mappings for a service
	GetServiceMappings(ctx context.Context, in *ServiceID, opts ...grpc.CallOption) (*JsonMappingResponseList, error)
	// add any host mapping
	AddAnyHostMapping(ctx context.Context, in *AnyMappingRequest, opts ...grpc.CallOption) (*AnyMappingResponse, error)
}

type uRLMapperClient struct {
	cc *grpc.ClientConn
}

func NewURLMapperClient(cc *grpc.ClientConn) URLMapperClient {
	return &uRLMapperClient{cc}
}

func (c *uRLMapperClient) GetJsonMappingWithUser(ctx context.Context, in *GetJsonMappingRequest, opts ...grpc.CallOption) (*JsonMappingResponse, error) {
	out := new(JsonMappingResponse)
	err := grpc.Invoke(ctx, "/urlmapper.URLMapper/GetJsonMappingWithUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLMapperClient) GetJsonMapping(ctx context.Context, in *GetJsonMappingRequest, opts ...grpc.CallOption) (*JsonMappingResponse, error) {
	out := new(JsonMappingResponse)
	err := grpc.Invoke(ctx, "/urlmapper.URLMapper/GetJsonMapping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLMapperClient) GetJsonMappings(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*JsonMappingResponseList, error) {
	out := new(JsonMappingResponseList)
	err := grpc.Invoke(ctx, "/urlmapper.URLMapper/GetJsonMappings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLMapperClient) AddJsonMapping(ctx context.Context, in *JsonMapping, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/urlmapper.URLMapper/AddJsonMapping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLMapperClient) GetJsonDomains(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*DomainList, error) {
	out := new(DomainList)
	err := grpc.Invoke(ctx, "/urlmapper.URLMapper/GetJsonDomains", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLMapperClient) GetServiceMappings(ctx context.Context, in *ServiceID, opts ...grpc.CallOption) (*JsonMappingResponseList, error) {
	out := new(JsonMappingResponseList)
	err := grpc.Invoke(ctx, "/urlmapper.URLMapper/GetServiceMappings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLMapperClient) AddAnyHostMapping(ctx context.Context, in *AnyMappingRequest, opts ...grpc.CallOption) (*AnyMappingResponse, error) {
	out := new(AnyMappingResponse)
	err := grpc.Invoke(ctx, "/urlmapper.URLMapper/AddAnyHostMapping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for URLMapper service

type URLMapperServer interface {
	// get json mapping for URL and user
	GetJsonMappingWithUser(context.Context, *GetJsonMappingRequest) (*JsonMappingResponse, error)
	// get json mapping for URL
	GetJsonMapping(context.Context, *GetJsonMappingRequest) (*JsonMappingResponse, error)
	// get all json mappings
	GetJsonMappings(context.Context, *common.Void) (*JsonMappingResponseList, error)
	// add a json mapping
	AddJsonMapping(context.Context, *JsonMapping) (*common.Void, error)
	// get all domains "mapped" to jsonmultiplexer
	GetJsonDomains(context.Context, *common.Void) (*DomainList, error)
	// get mappings for a service
	GetServiceMappings(context.Context, *ServiceID) (*JsonMappingResponseList, error)
	// add any host mapping
	AddAnyHostMapping(context.Context, *AnyMappingRequest) (*AnyMappingResponse, error)
}

func RegisterURLMapperServer(s *grpc.Server, srv URLMapperServer) {
	s.RegisterService(&_URLMapper_serviceDesc, srv)
}

func _URLMapper_GetJsonMappingWithUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJsonMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLMapperServer).GetJsonMappingWithUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlmapper.URLMapper/GetJsonMappingWithUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLMapperServer).GetJsonMappingWithUser(ctx, req.(*GetJsonMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLMapper_GetJsonMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJsonMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLMapperServer).GetJsonMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlmapper.URLMapper/GetJsonMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLMapperServer).GetJsonMapping(ctx, req.(*GetJsonMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLMapper_GetJsonMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLMapperServer).GetJsonMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlmapper.URLMapper/GetJsonMappings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLMapperServer).GetJsonMappings(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLMapper_AddJsonMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonMapping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLMapperServer).AddJsonMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlmapper.URLMapper/AddJsonMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLMapperServer).AddJsonMapping(ctx, req.(*JsonMapping))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLMapper_GetJsonDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLMapperServer).GetJsonDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlmapper.URLMapper/GetJsonDomains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLMapperServer).GetJsonDomains(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLMapper_GetServiceMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLMapperServer).GetServiceMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlmapper.URLMapper/GetServiceMappings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLMapperServer).GetServiceMappings(ctx, req.(*ServiceID))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLMapper_AddAnyHostMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnyMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLMapperServer).AddAnyHostMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlmapper.URLMapper/AddAnyHostMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLMapperServer).AddAnyHostMapping(ctx, req.(*AnyMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _URLMapper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "urlmapper.URLMapper",
	HandlerType: (*URLMapperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJsonMappingWithUser",
			Handler:    _URLMapper_GetJsonMappingWithUser_Handler,
		},
		{
			MethodName: "GetJsonMapping",
			Handler:    _URLMapper_GetJsonMapping_Handler,
		},
		{
			MethodName: "GetJsonMappings",
			Handler:    _URLMapper_GetJsonMappings_Handler,
		},
		{
			MethodName: "AddJsonMapping",
			Handler:    _URLMapper_AddJsonMapping_Handler,
		},
		{
			MethodName: "GetJsonDomains",
			Handler:    _URLMapper_GetJsonDomains_Handler,
		},
		{
			MethodName: "GetServiceMappings",
			Handler:    _URLMapper_GetServiceMappings_Handler,
		},
		{
			MethodName: "AddAnyHostMapping",
			Handler:    _URLMapper_AddAnyHostMapping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/golang.yacloud.eu/apis/urlmapper/urlmapper.proto",
}

func init() {
	proto.RegisterFile("protos/golang.yacloud.eu/apis/urlmapper/urlmapper.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x93, 0xd0, 0xe0, 0x09, 0x0a, 0xea, 0x42, 0x83, 0x1b, 0x02, 0xb2, 0xf6, 0x80, 0x72,
	0x72, 0x50, 0x10, 0x70, 0x81, 0x43, 0x1a, 0x4b, 0xc1, 0xa8, 0xad, 0x22, 0xa3, 0x52, 0xa9, 0xe2,
	0x62, 0xe2, 0x55, 0x6a, 0x29, 0xde, 0x35, 0xde, 0x35, 0x28, 0x47, 0xf8, 0x03, 0x7e, 0x83, 0xaf,
	0x44, 0x5d, 0xaf, 0xed, 0x75, 0x70, 0x28, 0x07, 0x4e, 0xf1, 0xcc, 0xee, 0x7b, 0x33, 0x3b, 0xef,
	0x65, 0xe0, 0x75, 0x92, 0x32, 0xc1, 0xf8, 0x64, 0xcd, 0x36, 0x01, 0x5d, 0x3b, 0xdb, 0x60, 0xb5,
	0x61, 0x59, 0xe8, 0x90, 0x6c, 0x12, 0x24, 0x11, 0x9f, 0x64, 0xe9, 0x26, 0x0e, 0x92, 0x84, 0xa4,
	0xd5, 0x97, 0x23, 0x11, 0xc8, 0x2c, 0x13, 0x43, 0x47, 0x81, 0x57, 0x8c, 0xa6, 0x41, 0xf8, 0x8d,
	0xb1, 0xd0, 0xa1, 0x44, 0xe4, 0x04, 0x2b, 0x16, 0xc7, 0x8c, 0xaa, 0x9f, 0x1c, 0x8a, 0xbf, 0x1b,
	0xd0, 0x7b, 0xcf, 0x19, 0x3d, 0x0b, 0x92, 0x24, 0xa2, 0x6b, 0xd4, 0x87, 0x96, 0xe7, 0x5a, 0x86,
	0x6d, 0x8c, 0x3b, 0x7e, 0xcb, 0x73, 0xd1, 0x00, 0x0e, 0x5c, 0x16, 0x07, 0x11, 0xb5, 0x5a, 0xb6,
	0x31, 0x36, 0x7d, 0x15, 0x21, 0x04, 0x9d, 0x65, 0x20, 0xae, 0xad, 0xb6, 0xcc, 0xca, 0x6f, 0x34,
	0x02, 0xf3, 0x03, 0x49, 0xbf, 0x46, 0x2b, 0xe2, 0xb9, 0x56, 0x47, 0x1e, 0x54, 0x09, 0x64, 0x41,
	0x77, 0x91, 0xb2, 0x2c, 0xf1, 0x5c, 0xeb, 0x8e, 0x3c, 0x2b, 0x42, 0x3c, 0x87, 0xa3, 0x05, 0x11,
	0x5a, 0x17, 0x3e, 0xf9, 0x92, 0x11, 0x2e, 0xb4, 0xe2, 0x46, 0x63, 0xf1, 0x56, 0x55, 0x1c, 0x47,
	0xf0, 0xa0, 0xc6, 0xc0, 0x13, 0x46, 0x39, 0x41, 0xcf, 0xa1, 0xab, 0x52, 0x92, 0xa3, 0x37, 0x1d,
	0x38, 0xd5, 0xf4, 0x74, 0x40, 0x71, 0x0d, 0xd9, 0xd0, 0x5b, 0xf8, 0xcb, 0xb9, 0x6a, 0x5c, 0xd5,
	0xd0, 0x53, 0xf8, 0x12, 0x1e, 0x35, 0x94, 0x3a, 0x8d, 0xb8, 0x40, 0x6f, 0xc0, 0x2c, 0x62, 0x6e,
	0x19, 0x76, 0x7b, 0xdc, 0x9b, 0x3e, 0xdd, 0x53, 0x50, 0x5d, 0xf3, 0x2b, 0x00, 0x7e, 0x06, 0x90,
	0xbf, 0x50, 0x72, 0x59, 0xd0, 0xcd, 0xa3, 0x9c, 0xc9, 0xf4, 0x8b, 0x10, 0x3f, 0xd6, 0x06, 0xad,
	0x29, 0x66, 0xde, 0x28, 0x86, 0x3f, 0x41, 0x7f, 0x46, 0xb7, 0xef, 0x18, 0x17, 0xfb, 0x34, 0x1d,
	0xe9, 0xe3, 0x3b, 0xb9, 0xfb, 0xeb, 0xc7, 0x71, 0x47, 0xa4, 0x19, 0x69, 0x52, 0xb1, 0xbd, 0xa3,
	0x22, 0xf6, 0xe0, 0x70, 0x46, 0xb7, 0x3b, 0x3a, 0x15, 0x7a, 0x18, 0x9a, 0x19, 0x6c, 0xe8, 0x29,
	0xd4, 0x79, 0x10, 0x97, 0x63, 0xd4, 0x52, 0x78, 0x0c, 0x48, 0xa7, 0x52, 0x82, 0x35, 0x70, 0x4d,
	0x7f, 0x76, 0xc0, 0xbc, 0xf0, 0x4f, 0xcf, 0xe4, 0x10, 0xd1, 0x15, 0x0c, 0xea, 0x76, 0xb9, 0x8c,
	0xc4, 0xf5, 0x05, 0x27, 0x29, 0xb2, 0xb5, 0x51, 0x37, 0x3a, 0x6a, 0x78, 0x8b, 0x18, 0xc8, 0x87,
	0x7e, 0x1d, 0xf8, 0x1f, 0x38, 0xe7, 0x70, 0xbf, 0x0e, 0xe4, 0xe8, 0x9e, 0xa3, 0xfe, 0x84, 0x1f,
	0x59, 0x14, 0x0e, 0xf1, 0xdf, 0x09, 0xa4, 0x19, 0x5e, 0x41, 0x7f, 0x16, 0x86, 0x7a, 0x63, 0x7b,
	0x8c, 0x3c, 0xac, 0x71, 0xa3, 0x97, 0xe5, 0x83, 0x94, 0x79, 0x76, 0x6a, 0x1f, 0x69, 0x2c, 0x9a,
	0xf7, 0xce, 0x01, 0x2d, 0x88, 0x50, 0x6a, 0x95, 0x6d, 0x3f, 0xd4, 0x2e, 0x97, 0x96, 0xf8, 0xa7,
	0xf6, 0x97, 0x70, 0x38, 0x0b, 0xc3, 0x1d, 0x5f, 0x8e, 0x34, 0xe0, 0x1f, 0xa6, 0x1a, 0x3e, 0xd9,
	0x73, 0x9a, 0xb3, 0x9e, 0xbc, 0x85, 0x63, 0x92, 0x95, 0x3b, 0xf2, 0x66, 0xbf, 0x55, 0xf7, 0xaf,
	0xec, 0xdb, 0x56, 0xe8, 0xe7, 0x03, 0xb9, 0xfe, 0x5e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x0b,
	0x03, 0xc7, 0x16, 0x74, 0x05, 0x00, 0x00,
}


